Tweak production deployment to add server=true

diff --git a/.deliver/config b/.deliver/config
--- a/.deliver/config
+++ b/.deliver/config
@@ -1,4 +1,8 @@
+#!/usr/bin/env bash
+
 APP="shovik_com"
+
+AUTO_VERSION="commit-count+branch+git-revision"
 
 BUILD_HOST="138.197.21.158"
 BUILD_USER="app"
@@ -12,36 +16,49 @@ PRODUCTION_USER="app"
 
 DELIVER_TO="/srv/www"
 
-# For *Phoenix* projects, symlink prod.secret.exs to our tmp source
+# copies the prod.secret.exs file you keep sequestered on your build
+# machine into the build directory.
 pre_erlang_get_and_update_deps() {
-  local _prod_secret_path="/srv/www/prod.secret.exs"
+  # copy it on the build host to the build directory when building
+  local _secret_config_file_on_build_host="/srv/www/prod.secret.exs"
   if [ "$TARGET_MIX_ENV" = "prod" ]; then
+    status "Linking '$_secret_config_file_on_build_host' to build config dir"
     __sync_remote "
-      ln -sfn '$_prod_secret_path' '$BUILD_AT/config/prod.secret.exs'
+      ln -sfn '$_secret_config_file_on_build_host' '$BUILD_AT/config/prod.secret.exs'
     "
   fi
 }
 
+# runs the phoenix.digest mix command, which gets rid of a missing
+# manifest file error
 pre_erlang_clean_compile() {
-  status "Preparing assets with: brunch build and phoenix.digest"
+  status "Installing NodeJS dependencies"
   __sync_remote "
-    # runs the commands on the build host
     [ -f ~/.profile ] && source ~/.profile # load profile (optional)
-
-    # fail if any command fails (recommended)
-    set -e
-
-    # enter the build directory on the build host (required)
-    cd '$BUILD_AT'
-
+    set -e # fail if any command fails (recommended)
+    cd '$BUILD_AT' # enter the build directory on the build host (required)
+    # prepare something
     mkdir -p priv/static # required by the phoenix.digest task
-
-    # installing npm dependencies
-    npm install
-
-    # building brunch
-    brunch build --production
-
+    # run your custom task
+    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' npm install
+  "
+  status "Building frontend items"
+  __sync_remote "
+    [ -f ~/.profile ] && source ~/.profile # load profile (optional)
+    set -e # fail if any command fails (recommended)
+    cd '$BUILD_AT' # enter the build directory on the build host (required)
+    # prepare something
+    mkdir -p priv/static # required by the phoenix.digest task
+    # run your custom task
+    APP='$APP' MIX_ENV='$TARGET_MIX_ENV' npm run deploy
+  "
+  status "Running phoenix.digest" # log output prepended with "----->"
+  __sync_remote " # runs the commands on the build host
+    [ -f ~/.profile ] && source ~/.profile # load profile (optional)
+    set -e # fail if any command fails (recommended)
+    cd '$BUILD_AT' # enter the build directory on the build host (required)
+    # prepare something
+    mkdir -p priv/static # required by the phoenix.digest task
     # run your custom task
     APP='$APP' MIX_ENV='$TARGET_MIX_ENV' $MIX_CMD phoenix.digest $SILENCE
   "
